// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     union.avsc
 */
package avro

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
)

func writeIp_address(r Ip_address, w io.Writer) error {
	_, err := w.Write(r[:])
	return err
}

type Ip_address [16]byte

func (_ *Ip_address) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Ip_address) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Ip_address) SetLong(v int64) { panic("Unsupported operation") }
func (_ *Ip_address) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Ip_address) SetDouble(v float64) { panic("Unsupported operation") }
func (r *Ip_address) SetBytes(v []byte) { 
	copy((*r)[:], v)
}
func (_ *Ip_address) SetString(v string) { panic("Unsupported operation") }
func (_ *Ip_address) SetUnionElem(v int64) { panic("Unsupported operation") }
func (_ *Ip_address) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *Ip_address) Clear(i int) { panic("Unsupported operation") }
func (_ *Ip_address) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Ip_address) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Ip_address) Finalize() { }
func (_ *Ip_address) SetDefault(i int) { panic("Unsupported operation") }

