// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v8/compiler"
	"github.com/actgardner/gogen-avro/v8/vm"
	"github.com/actgardner/gogen-avro/v8/vm/types"
)

type UnionBodyworksDataTypeEnum int

const (
	UnionBodyworksDataTypeEnumBodyworksData UnionBodyworksDataTypeEnum = 1
)

type UnionBodyworksData struct {
	Null          *types.NullVal
	BodyworksData BodyworksData
	UnionType     UnionBodyworksDataTypeEnum
}

func writeUnionBodyworksData(r *UnionBodyworksData, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionBodyworksDataTypeEnumBodyworksData:
		return writeBodyworksData(r.BodyworksData, w)
	}
	return fmt.Errorf("invalid value for *UnionBodyworksData")
}

func NewUnionBodyworksData() *UnionBodyworksData {
	return &UnionBodyworksData{}
}

func (r *UnionBodyworksData) Serialize(w io.Writer) error {
	return writeUnionBodyworksData(r, w)
}

func DeserializeUnionBodyworksData(r io.Reader) (*UnionBodyworksData, error) {
	t := NewUnionBodyworksData()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionBodyworksDataFromSchema(r io.Reader, schema string) (*UnionBodyworksData, error) {
	t := NewUnionBodyworksData()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionBodyworksData) Schema() string {
	return "[\"null\",{\"doc\":\"Common information related to the event which must be included in any clean event\",\"fields\":[{\"default\":null,\"doc\":\"Unique identifier for the event used for de-duplication and tracing.\",\"name\":\"uuid\",\"type\":[\"null\",{\"doc\":\"A Universally Unique Identifier, in canonical form in lowercase. Example: de305d54-75b4-431b-adb2-eb6b9e546014\",\"fields\":[{\"default\":\"\",\"name\":\"uuid\",\"type\":\"string\"}],\"name\":\"UUID\",\"namespace\":\"bodyworks.datatype\",\"type\":\"record\"}]},{\"default\":null,\"doc\":\"Fully qualified name of the host that generated the event that generated the data.\",\"name\":\"hostname\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"doc\":\"Trace information not redundant with this object\",\"name\":\"trace\",\"type\":[\"null\",{\"doc\":\"Trace\",\"fields\":[{\"default\":null,\"doc\":\"Trace Identifier\",\"name\":\"traceId\",\"type\":[\"null\",{\"doc\":\"A Universally Unique Identifier, in canonical form in lowercase. Example: de305d54-75b4-431b-adb2-eb6b9e546014\",\"fields\":[{\"default\":\"\",\"name\":\"uuid\",\"type\":\"string\"}],\"name\":\"UUID\",\"namespace\":\"headerworks.datatype\",\"type\":\"record\"}]}],\"name\":\"Trace\",\"type\":\"record\"}]}],\"name\":\"Data\",\"namespace\":\"bodyworks\",\"type\":\"record\"}]"
}

func (_ *UnionBodyworksData) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionBodyworksData) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionBodyworksData) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionBodyworksData) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionBodyworksData) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionBodyworksData) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionBodyworksData) SetLong(v int64) {

	r.UnionType = (UnionBodyworksDataTypeEnum)(v)
}

func (r *UnionBodyworksData) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.BodyworksData = NewBodyworksData()
		return &types.Record{Target: (&r.BodyworksData)}
	}
	panic("Unknown field index")
}
func (_ *UnionBodyworksData) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionBodyworksData) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionBodyworksData) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionBodyworksData) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionBodyworksData) Finalize()                        {}

func (r *UnionBodyworksData) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionBodyworksDataTypeEnumBodyworksData:
		return json.Marshal(map[string]interface{}{"bodyworks.Data": r.BodyworksData})
	}
	return nil, fmt.Errorf("invalid value for *UnionBodyworksData")
}

func (r *UnionBodyworksData) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["bodyworks.Data"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.BodyworksData)
	}
	return fmt.Errorf("invalid value for *UnionBodyworksData")
}
