// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v8/compiler"
	"github.com/actgardner/gogen-avro/v8/vm"
	"github.com/actgardner/gogen-avro/v8/vm/types"
)

type UnionHeaderworksTraceTypeEnum int

const (
	UnionHeaderworksTraceTypeEnumHeaderworksTrace UnionHeaderworksTraceTypeEnum = 1
)

type UnionHeaderworksTrace struct {
	Null             *types.NullVal
	HeaderworksTrace HeaderworksTrace
	UnionType        UnionHeaderworksTraceTypeEnum
}

func writeUnionHeaderworksTrace(r *UnionHeaderworksTrace, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionHeaderworksTraceTypeEnumHeaderworksTrace:
		return writeHeaderworksTrace(r.HeaderworksTrace, w)
	}
	return fmt.Errorf("invalid value for *UnionHeaderworksTrace")
}

func NewUnionHeaderworksTrace() *UnionHeaderworksTrace {
	return &UnionHeaderworksTrace{}
}

func (r *UnionHeaderworksTrace) Serialize(w io.Writer) error {
	return writeUnionHeaderworksTrace(r, w)
}

func DeserializeUnionHeaderworksTrace(r io.Reader) (*UnionHeaderworksTrace, error) {
	t := NewUnionHeaderworksTrace()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionHeaderworksTraceFromSchema(r io.Reader, schema string) (*UnionHeaderworksTrace, error) {
	t := NewUnionHeaderworksTrace()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionHeaderworksTrace) Schema() string {
	return "[\"null\",{\"doc\":\"Trace\",\"fields\":[{\"default\":null,\"doc\":\"Trace Identifier\",\"name\":\"traceId\",\"type\":[\"null\",{\"doc\":\"A Universally Unique Identifier, in canonical form in lowercase. Example: de305d54-75b4-431b-adb2-eb6b9e546014\",\"fields\":[{\"default\":\"\",\"name\":\"uuid\",\"type\":\"string\"}],\"name\":\"UUID\",\"namespace\":\"headerworks.datatype\",\"type\":\"record\"}]}],\"name\":\"Trace\",\"type\":\"record\"}]"
}

func (_ *UnionHeaderworksTrace) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionHeaderworksTrace) SetLong(v int64) {

	r.UnionType = (UnionHeaderworksTraceTypeEnum)(v)
}

func (r *UnionHeaderworksTrace) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.HeaderworksTrace = NewHeaderworksTrace()
		return &types.Record{Target: (&r.HeaderworksTrace)}
	}
	panic("Unknown field index")
}
func (_ *UnionHeaderworksTrace) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionHeaderworksTrace) Finalize()                        {}

func (r *UnionHeaderworksTrace) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionHeaderworksTraceTypeEnumHeaderworksTrace:
		return json.Marshal(map[string]interface{}{"headerworks.Trace": r.HeaderworksTrace})
	}
	return nil, fmt.Errorf("invalid value for *UnionHeaderworksTrace")
}

func (r *UnionHeaderworksTrace) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["headerworks.Trace"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.HeaderworksTrace)
	}
	return fmt.Errorf("invalid value for *UnionHeaderworksTrace")
}
