// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v8/compiler"
	"github.com/actgardner/gogen-avro/v8/vm"
	"github.com/actgardner/gogen-avro/v8/vm/types"
)

type UnionIntLongFloatDoubleStringBoolTypeEnum int

const (
	UnionIntLongFloatDoubleStringBoolTypeEnumInt UnionIntLongFloatDoubleStringBoolTypeEnum = 0

	UnionIntLongFloatDoubleStringBoolTypeEnumLong UnionIntLongFloatDoubleStringBoolTypeEnum = 1

	UnionIntLongFloatDoubleStringBoolTypeEnumFloat UnionIntLongFloatDoubleStringBoolTypeEnum = 2

	UnionIntLongFloatDoubleStringBoolTypeEnumDouble UnionIntLongFloatDoubleStringBoolTypeEnum = 3

	UnionIntLongFloatDoubleStringBoolTypeEnumString UnionIntLongFloatDoubleStringBoolTypeEnum = 4

	UnionIntLongFloatDoubleStringBoolTypeEnumBool UnionIntLongFloatDoubleStringBoolTypeEnum = 5
)

type UnionIntLongFloatDoubleStringBool struct {
	Int       int32
	Long      int64
	Float     float32
	Double    float64
	String    string
	Bool      bool
	Null      *types.NullVal
	UnionType UnionIntLongFloatDoubleStringBoolTypeEnum
}

func writeUnionIntLongFloatDoubleStringBool(r *UnionIntLongFloatDoubleStringBool, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(6, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionIntLongFloatDoubleStringBoolTypeEnumInt:
		return vm.WriteInt(r.Int, w)
	case UnionIntLongFloatDoubleStringBoolTypeEnumLong:
		return vm.WriteLong(r.Long, w)
	case UnionIntLongFloatDoubleStringBoolTypeEnumFloat:
		return vm.WriteFloat(r.Float, w)
	case UnionIntLongFloatDoubleStringBoolTypeEnumDouble:
		return vm.WriteDouble(r.Double, w)
	case UnionIntLongFloatDoubleStringBoolTypeEnumString:
		return vm.WriteString(r.String, w)
	case UnionIntLongFloatDoubleStringBoolTypeEnumBool:
		return vm.WriteBool(r.Bool, w)
	}
	return fmt.Errorf("invalid value for *UnionIntLongFloatDoubleStringBool")
}

func NewUnionIntLongFloatDoubleStringBool() *UnionIntLongFloatDoubleStringBool {
	return &UnionIntLongFloatDoubleStringBool{}
}

func (r *UnionIntLongFloatDoubleStringBool) Serialize(w io.Writer) error {
	return writeUnionIntLongFloatDoubleStringBool(r, w)
}

func DeserializeUnionIntLongFloatDoubleStringBool(r io.Reader) (*UnionIntLongFloatDoubleStringBool, error) {
	t := NewUnionIntLongFloatDoubleStringBool()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionIntLongFloatDoubleStringBoolFromSchema(r io.Reader, schema string) (*UnionIntLongFloatDoubleStringBool, error) {
	t := NewUnionIntLongFloatDoubleStringBool()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionIntLongFloatDoubleStringBool) Schema() string {
	return "[\"int\",\"long\",\"float\",\"double\",\"string\",\"boolean\",\"null\"]"
}

func (_ *UnionIntLongFloatDoubleStringBool) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionIntLongFloatDoubleStringBool) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionIntLongFloatDoubleStringBool) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionIntLongFloatDoubleStringBool) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionIntLongFloatDoubleStringBool) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionIntLongFloatDoubleStringBool) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionIntLongFloatDoubleStringBool) SetLong(v int64) {

	r.UnionType = (UnionIntLongFloatDoubleStringBoolTypeEnum)(v)
}

func (r *UnionIntLongFloatDoubleStringBool) Get(i int) types.Field {

	switch i {
	case 0:
		return &types.Int{Target: (&r.Int)}
	case 1:
		return &types.Long{Target: (&r.Long)}
	case 2:
		return &types.Float{Target: (&r.Float)}
	case 3:
		return &types.Double{Target: (&r.Double)}
	case 4:
		return &types.String{Target: (&r.String)}
	case 5:
		return &types.Boolean{Target: (&r.Bool)}
	case 6:
		return r.Null
	}
	panic("Unknown field index")
}
func (_ *UnionIntLongFloatDoubleStringBool) NullField(i int)  { panic("Unsupported operation") }
func (_ *UnionIntLongFloatDoubleStringBool) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionIntLongFloatDoubleStringBool) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionIntLongFloatDoubleStringBool) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionIntLongFloatDoubleStringBool) Finalize()                {}

func (r *UnionIntLongFloatDoubleStringBool) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionIntLongFloatDoubleStringBoolTypeEnumInt:
		return json.Marshal(map[string]interface{}{"int": r.Int})
	case UnionIntLongFloatDoubleStringBoolTypeEnumLong:
		return json.Marshal(map[string]interface{}{"long": r.Long})
	case UnionIntLongFloatDoubleStringBoolTypeEnumFloat:
		return json.Marshal(map[string]interface{}{"float": r.Float})
	case UnionIntLongFloatDoubleStringBoolTypeEnumDouble:
		return json.Marshal(map[string]interface{}{"double": r.Double})
	case UnionIntLongFloatDoubleStringBoolTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	case UnionIntLongFloatDoubleStringBoolTypeEnumBool:
		return json.Marshal(map[string]interface{}{"boolean": r.Bool})
	}
	return nil, fmt.Errorf("invalid value for *UnionIntLongFloatDoubleStringBool")
}

func (r *UnionIntLongFloatDoubleStringBool) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["int"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.Int)
	}
	if value, ok := fields["long"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Long)
	}
	if value, ok := fields["float"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.Float)
	}
	if value, ok := fields["double"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.Double)
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 4
		return json.Unmarshal([]byte(value), &r.String)
	}
	if value, ok := fields["boolean"]; ok {
		r.UnionType = 5
		return json.Unmarshal([]byte(value), &r.Bool)
	}
	return fmt.Errorf("invalid value for *UnionIntLongFloatDoubleStringBool")
}
