#!/bin/bash -x

set -e

pkgs=$*
if [ $# -eq 0 ]; then
	pkgs=./...
fi

go install ./cmd/...
# Clean out all the generated files so we know we're starting with a clean slate.
rm $(find . -name '*.go' | xargs grep -l '^// Code generated by github.com/actgardner/gogen-avro')
go generate ./...
go test $pkgs
