// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v8/vm"
	"github.com/actgardner/gogen-avro/v8/vm/types"
)

func writeArrayUnionInt(r []*UnionInt, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionInt(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionIntWrapper struct {
	Target *[]*UnionInt
}

func (_ *ArrayUnionIntWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayUnionIntWrapper) Finalize()                        {}
func (_ *ArrayUnionIntWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayUnionIntWrapper) NullField(i int) {
	(*r.Target)[len(*r.Target)-1] = nil
}

func (r *ArrayUnionIntWrapper) AppendArray() types.Field {
	var v *UnionInt
	v = NewUnionInt()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
