// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

type UnionDatatypeUUIDTypeEnum int

const (
	UnionDatatypeUUIDTypeEnumDatatypeUUID UnionDatatypeUUIDTypeEnum = 1
)

type UnionDatatypeUUID struct {
	Null         *types.NullVal
	DatatypeUUID DatatypeUUID
	UnionType    UnionDatatypeUUIDTypeEnum
}

func writeUnionDatatypeUUID(r *UnionDatatypeUUID, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionDatatypeUUIDTypeEnumDatatypeUUID:
		return writeDatatypeUUID(r.DatatypeUUID, w)
	}
	return fmt.Errorf("invalid value for *UnionDatatypeUUID")
}

func NewUnionDatatypeUUID() *UnionDatatypeUUID {
	return &UnionDatatypeUUID{}
}

func (r *UnionDatatypeUUID) Serialize(w io.Writer) error {
	return writeUnionDatatypeUUID(r, w)
}

func DeserializeUnionDatatypeUUID(r io.Reader) (*UnionDatatypeUUID, error) {
	t := NewUnionDatatypeUUID()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionDatatypeUUIDFromSchema(r io.Reader, schema string) (*UnionDatatypeUUID, error) {
	t := NewUnionDatatypeUUID()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionDatatypeUUID) Schema() string {
	return "[\"null\",{\"doc\":\"A Universally Unique Identifier, in canonical form in lowercase. Example: de305d54-75b4-431b-adb2-eb6b9e546014\",\"fields\":[{\"default\":\"\",\"name\":\"uuid\",\"type\":\"string\"}],\"name\":\"UUID\",\"namespace\":\"bodyworks.datatype\",\"type\":\"record\"}]"
}

func (_ *UnionDatatypeUUID) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionDatatypeUUID) SetLong(v int64) {

	r.UnionType = (UnionDatatypeUUIDTypeEnum)(v)
}

func (r *UnionDatatypeUUID) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.DatatypeUUID = NewDatatypeUUID()
		return &types.Record{Target: (&r.DatatypeUUID)}
	}
	panic("Unknown field index")
}
func (_ *UnionDatatypeUUID) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionDatatypeUUID) Finalize()                        {}

func (r *UnionDatatypeUUID) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionDatatypeUUIDTypeEnumDatatypeUUID:
		return json.Marshal(map[string]interface{}{"bodyworks.datatype.UUID": r.DatatypeUUID})
	}
	return nil, fmt.Errorf("invalid value for *UnionDatatypeUUID")
}

func (r *UnionDatatypeUUID) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["bodyworks.datatype.UUID"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.DatatypeUUID)
	}
	return fmt.Errorf("invalid value for *UnionDatatypeUUID")
}
