// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v8/compiler"
	"github.com/actgardner/gogen-avro/v8/container"
	"github.com/actgardner/gogen-avro/v8/vm"
)

func NewRecord1Writer(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewRecord1()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type Record1Reader struct {
	r io.Reader
	p *vm.Program
}

func NewRecord1Reader(r io.Reader) (*Record1Reader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewRecord1()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &Record1Reader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r Record1Reader) Read() (*Record1, error) {
	t := NewRecord1()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
