// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     block.avsc
 *     header.avsc
 */
package avro

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
)

func writeMagic(r Magic, w io.Writer) error {
	_, err := w.Write(r[:])
	return err
}

type Magic [4]byte

func (_ *Magic) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Magic) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Magic) SetLong(v int64) { panic("Unsupported operation") }
func (_ *Magic) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Magic) SetDouble(v float64) { panic("Unsupported operation") }
func (r *Magic) SetBytes(v []byte) { 
	copy((*r)[:], v)
}
func (_ *Magic) SetString(v string) { panic("Unsupported operation") }
func (_ *Magic) SetUnionElem(v int64) { panic("Unsupported operation") }
func (_ *Magic) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *Magic) Clear(i int) { panic("Unsupported operation") }
func (_ *Magic) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Magic) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Magic) Finalize() { }
func (_ *Magic) SetDefault(i int) { panic("Unsupported operation") }

