// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v8/compiler"
	"github.com/actgardner/gogen-avro/v8/container"
	"github.com/actgardner/gogen-avro/v8/vm"
)

func NewRecordBarWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewRecordBar()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type RecordBarReader struct {
	r io.Reader
	p *vm.Program
}

func NewRecordBarReader(r io.Reader) (*RecordBarReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewRecordBar()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &RecordBarReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r RecordBarReader) Read() (RecordBar, error) {
	t := NewRecordBar()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
