// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v8/compiler"
	"github.com/actgardner/gogen-avro/v8/vm"
	"github.com/actgardner/gogen-avro/v8/vm/types"
)

var _ = fmt.Printf

type RecordFoo struct {
	Id string `json:"id"`
}

const RecordFooAvroCRC64Fingerprint = "\x94\f\x14v\xb3\x98ߴ"

func NewRecordFoo() *RecordFoo {
	return &RecordFoo{}
}

func DeserializeRecordFoo(r io.Reader) (*RecordFoo, error) {
	t := NewRecordFoo()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func DeserializeRecordFooFromSchema(r io.Reader, schema string) (*RecordFoo, error) {
	t := NewRecordFoo()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func writeRecordFoo(r *RecordFoo, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Id, w)
	if err != nil {
		return err
	}
	return err
}

func (r *RecordFoo) Serialize(w io.Writer) error {
	return writeRecordFoo(r, w)
}

func (r *RecordFoo) Schema() string {
	return "{\"fields\":[{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"RecordFoo\",\"type\":\"record\"}"
}

func (r *RecordFoo) SchemaName() string {
	return "RecordFoo"
}

func (_ *RecordFoo) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *RecordFoo) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *RecordFoo) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *RecordFoo) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *RecordFoo) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *RecordFoo) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *RecordFoo) SetString(v string)   { panic("Unsupported operation") }
func (_ *RecordFoo) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RecordFoo) Get(i int) types.Field {
	switch i {
	case 0:
		return &types.String{Target: &r.Id}
	}
	panic("Unknown field index")
}

func (r *RecordFoo) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *RecordFoo) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ *RecordFoo) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RecordFoo) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *RecordFoo) Finalize()                        {}

func (_ *RecordFoo) AvroCRC64Fingerprint() []byte {
	return []byte(RecordFooAvroCRC64Fingerprint)
}

func (r *RecordFoo) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["id"], err = json.Marshal(r.Id)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *RecordFoo) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for id")
	}
	return nil
}
