// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
package avro

import (
	"errors"
	"io"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullStringIntTypeEnum int

const (
	UnionNullStringIntTypeEnumString UnionNullStringIntTypeEnum = 1

	UnionNullStringIntTypeEnumInt UnionNullStringIntTypeEnum = 2
)

type UnionNullStringInt struct { 
	String string

	Int int32

	UnionType UnionNullStringIntTypeEnum
}

func writeUnionNullStringInt(r *UnionNullStringInt, w io.Writer) error { 
	if r == nil {
		return vm.WriteLong(int64(0), w)
	} 
	if err := vm.WriteLong(int64(r.UnionType), w); err != nil {
		return err
	}
	switch r.UnionType{ 
	case UnionNullStringIntTypeEnumString:
		return vm.WriteString(r.String, w)
	case UnionNullStringIntTypeEnumInt:
		return vm.WriteInt(r.Int, w)
	}
	return errors.New("invalid value for *UnionNullStringInt")
}

func (_ *UnionNullStringInt) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullStringInt) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullStringInt) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullStringInt) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullStringInt) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullStringInt) SetString(v string) { panic("Unsupported operation") }

func (r *UnionNullStringInt) SetLong(v int64) { 
	r.UnionType = (UnionNullStringIntTypeEnum)(v)
}

func (r *UnionNullStringInt) Get(i int) types.Field {
	switch (i) { 
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	case 2:
		
		
		return (*types.Int)(&r.Int)
		
	
	}
	panic("Unknown field index")
}

func (r *UnionNullStringInt) Clear(i int) { panic("Unsupported operation") }
func (_ *UnionNullStringInt) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullStringInt) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullStringInt) ClearMap(key string) { panic("Unsupported operation") }
func (_ *UnionNullStringInt) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullStringInt) Finalize()  { }
