// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     recursive.avsc
 */
package avro

import (
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)

type RecursiveFieldUnionTypeEnum int

const (
	RecursiveFieldUnionTypeEnumRecursiveUnionTestRecord RecursiveFieldUnionTypeEnum = 1
)

type RecursiveFieldUnion struct {
	Null                     *types.NullVal
	RecursiveUnionTestRecord *RecursiveUnionTestRecord
	UnionType                RecursiveFieldUnionTypeEnum
}

func writeRecursiveFieldUnion(r *RecursiveFieldUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case RecursiveFieldUnionTypeEnumRecursiveUnionTestRecord:
		return writeRecursiveUnionTestRecord(r.RecursiveUnionTestRecord, w)
	}
	return fmt.Errorf("invalid value for *RecursiveFieldUnion")
}

func NewRecursiveFieldUnion() *RecursiveFieldUnion {
	return &RecursiveFieldUnion{}
}

func (_ *RecursiveFieldUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *RecursiveFieldUnion) SetLong(v int64) {
	r.UnionType = (RecursiveFieldUnionTypeEnum)(v)
}
func (r *RecursiveFieldUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.RecursiveUnionTestRecord = NewRecursiveUnionTestRecord()
		return r.RecursiveUnionTestRecord
	}
	panic("Unknown field index")
}
func (_ *RecursiveFieldUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *RecursiveFieldUnion) Finalize()                        {}
