// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     namespace.avsc
 */
package avro

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullBodyworksDataTypeEnum int
const (

	 UnionNullBodyworksDataTypeEnumNull UnionNullBodyworksDataTypeEnum = 0

	 UnionNullBodyworksDataTypeEnumBodyworksData UnionNullBodyworksDataTypeEnum = 1

)

type UnionNullBodyworksData struct {

	Null *types.NullVal

	BodyworksData *BodyworksData

	UnionType UnionNullBodyworksDataTypeEnum
}

func writeUnionNullBodyworksData(r *UnionNullBodyworksData, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullBodyworksDataTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullBodyworksDataTypeEnumBodyworksData:
		return writeBodyworksData(r.BodyworksData, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullBodyworksData")
}

func NewUnionNullBodyworksData() *UnionNullBodyworksData {
	return &UnionNullBodyworksData{}
}

func (_ *UnionNullBodyworksData) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksData) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksData) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksData) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksData) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksData) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullBodyworksData) SetLong(v int64) { 
	r.UnionType = (UnionNullBodyworksDataTypeEnum)(v)
}
func (r *UnionNullBodyworksData) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.BodyworksData = NewBodyworksData()
		
		
		return r.BodyworksData
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullBodyworksData) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksData) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullBodyworksData) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullBodyworksData) Finalize()  { }
