// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     namespace.avsc
 */
package avro

import (
	"errors"
	"io"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullBodyworksDatatypeUUIDTypeEnum int

const (
	UnionNullBodyworksDatatypeUUIDTypeEnumBodyworksDatatypeUUID UnionNullBodyworksDatatypeUUIDTypeEnum = 1
)

type UnionNullBodyworksDatatypeUUID struct { 
	BodyworksDatatypeUUID BodyworksDatatypeUUID

	UnionType UnionNullBodyworksDatatypeUUIDTypeEnum
}

func writeUnionNullBodyworksDatatypeUUID(r *UnionNullBodyworksDatatypeUUID, w io.Writer) error { 
	if r == nil {
		return vm.WriteLong(int64(0), w)
	} 
	if err := vm.WriteLong(int64(r.UnionType), w); err != nil {
		return err
	}
	switch r.UnionType{ 
	case UnionNullBodyworksDatatypeUUIDTypeEnumBodyworksDatatypeUUID:
		return writeBodyworksDatatypeUUID(r.BodyworksDatatypeUUID, w)
	}
	return errors.New("invalid value for *UnionNullBodyworksDatatypeUUID")
}

func (_ *UnionNullBodyworksDatatypeUUID) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) SetString(v string) { panic("Unsupported operation") }

func (r *UnionNullBodyworksDatatypeUUID) SetLong(v int64) { 
	r.UnionType = (UnionNullBodyworksDatatypeUUIDTypeEnum)(v)
}

func (r *UnionNullBodyworksDatatypeUUID) Get(i int) types.Field {
	switch (i) { 
	case 1:
		
		r.BodyworksDatatypeUUID = BodyworksDatatypeUUID{}
		
		
		return &r.BodyworksDatatypeUUID
		
	
	}
	panic("Unknown field index")
}

func (r *UnionNullBodyworksDatatypeUUID) Clear(i int) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullBodyworksDatatypeUUID) Finalize()  { }
