// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     union.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type UnionStringBytesTypeEnum int

const (
	UnionStringBytesTypeEnumString UnionStringBytesTypeEnum = 0

	UnionStringBytesTypeEnumBytes UnionStringBytesTypeEnum = 1
)

type UnionStringBytes struct {
	String    string
	Bytes     []byte
	UnionType UnionStringBytesTypeEnum
}

func writeUnionStringBytes(r *UnionStringBytes, w io.Writer) error {

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionStringBytesTypeEnumString:
		return vm.WriteString(r.String, w)
	case UnionStringBytesTypeEnumBytes:
		return vm.WriteBytes(r.Bytes, w)
	}
	return fmt.Errorf("invalid value for *UnionStringBytes")
}

func NewUnionStringBytes() *UnionStringBytes {
	return &UnionStringBytes{}
}

func (_ *UnionStringBytes) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionStringBytes) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionStringBytes) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionStringBytes) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionStringBytes) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionStringBytes) SetString(v string)  { panic("Unsupported operation") }
func (r *UnionStringBytes) SetLong(v int64) {
	r.UnionType = (UnionStringBytesTypeEnum)(v)
}
func (r *UnionStringBytes) Get(i int) types.Field {
	switch i {
	case 0:
		return &types.String{Target: (&r.String)}
	case 1:
		return &types.Bytes{Target: (&r.Bytes)}
	}
	panic("Unknown field index")
}
func (_ *UnionStringBytes) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionStringBytes) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionStringBytes) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionStringBytes) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionStringBytes) Finalize()                        {}

func (r *UnionStringBytes) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case UnionStringBytesTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	case UnionStringBytesTypeEnumBytes:
		return json.Marshal(map[string]interface{}{"bytes": r.Bytes})
	}
	return nil, fmt.Errorf("invalid value for *UnionStringBytes")
}

func (r *UnionStringBytes) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.String)
	}
	if value, ok := fields["bytes"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Bytes)
	}
	return fmt.Errorf("invalid value for *UnionStringBytes")
}
