// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     fixed-default.avsc
 */
package avro

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
)

func writeTestFixedDefaultType(r TestFixedDefaultType, w io.Writer) error {
	_, err := w.Write(r[:])
	return err
}

type TestFixedDefaultType [12]byte

func (_ *TestFixedDefaultType) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) SetInt(v int32) { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) SetLong(v int64) { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) SetDouble(v float64) { panic("Unsupported operation") }
func (r *TestFixedDefaultType) SetBytes(v []byte) { 
	copy((*r)[:], v)
}
func (_ *TestFixedDefaultType) SetString(v string) { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) SetUnionElem(v int64) { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) Clear(i int) { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *TestFixedDefaultType) Finalize() { }
func (_ *TestFixedDefaultType) SetDefault(i int) { panic("Unsupported operation") }

